 name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop mein-cloudbroetchen-webserver || true
            docker rm mein-cloudbroetchen-webserver || true
            docker pull adam2605/adams-nginx:latest
            docker run -d -p 8080:80 --name mein-cloudbroetchen-webserver adam2605/adams-nginx:latest
