name: Build Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Code auschecken
      uses: actions/checkout@v4

    - name: Docker Image testweise bauen
      run: |
        docker build -t adams-nginx:latest .
        echo "🎉 Das Image wurde von der Pipeline erfolgreich gebaut!"
